/**
 * Locate this plugin's tree from a host slash-command wrapper.
 *
 * Claude Code sets CLAUDE_PLUGIN_ROOT. agy does not, under any name.
 * `agy plugin install` copies this tree to
 * `<homedir>/.gemini/config/plugins/antigravity`.
 *
 * Resolution happens in Node so an unset or empty CLAUDE_PLUGIN_ROOT cannot
 * collapse — via shell expansion — into `/scripts/commands/<verb>.mjs`.
 * The `node -e` snippet in `commands/*.md` is generated by
 * {@link hostBootstrapSource} and must stay free of `$` and `%` so bash,
 * cmd.exe, and PowerShell do not interpolate it.
 */

import os from "node:os";
import path from "node:path";

export const AGY_PLUGIN_INSTALL_SEGMENTS = Object.freeze([
  ".gemini",
  "config",
  "plugins",
  "antigravity",
]);

/**
 * @param {string} [homedir]
 * @returns {string}
 */
export function agyPluginInstallDir(homedir = os.homedir()) {
  return path.join(homedir, ...AGY_PLUGIN_INSTALL_SEGMENTS);
}

/**
 * @param {{ env?: NodeJS.ProcessEnv, homedir?: string }} [opts]
 * @returns {string}
 */
export function resolvePluginRoot({ env = process.env, homedir = os.homedir() } = {}) {
  const fromClaude =
    typeof env.CLAUDE_PLUGIN_ROOT === "string" ? env.CLAUDE_PLUGIN_ROOT.trim() : "";
  if (fromClaude) return fromClaude;
  return agyPluginInstallDir(homedir);
}

/**
 * @param {string} verb
 * @param {{ env?: NodeJS.ProcessEnv, homedir?: string }} [opts]
 * @returns {string}
 */
export function resolveVerbScript(verb, opts) {
  return path.join(resolvePluginRoot(opts), "scripts", "commands", `${verb}.mjs`);
}

/**
 * @param {string} scriptPath
 * @param {string} verb
 * @returns {string}
 */
export function missingRuntimeMessage(scriptPath, verb) {
  return (
    `antigravity-plugin: runtime not found at ${scriptPath}. ` +
    `Run: npx @southcarpet/antigravity-plugin ${verb}`
  );
}

const VERB_RE = /^[a-z]+$/;

/**
 * CommonJS source for `node -e "..."` in command wrappers. No `$` or `%`.
 *
 * @param {string} verb
 * @returns {string}
 */
export function hostBootstrapSource(verb) {
  if (!VERB_RE.test(verb)) {
    throw new Error(`hostBootstrapSource: invalid verb ${verb}`);
  }
  const segments = AGY_PLUGIN_INSTALL_SEGMENTS.map((s) => `'${s}'`).join(",");
  return (
    "const p=require('node:path');" +
    "const os=require('node:os');" +
    "const fs=require('node:fs');" +
    "const {spawnSync}=require('node:child_process');" +
    `const root=process.env.CLAUDE_PLUGIN_ROOT||p.join(os.homedir(),${segments});` +
    `const s=p.join(root,'scripts','commands','${verb}.mjs');` +
    `if(!fs.existsSync(s)){console.error('antigravity-plugin: runtime not found at '+s+'. Run: npx @southcarpet/antigravity-plugin ${verb}');process.exit(1)}` +
    "const r=spawnSync(process.execPath,[s].concat(process.argv.slice(1)),{stdio:'inherit'});" +
    `if(r.error){console.error('antigravity-plugin: failed to start '+s+': '+r.error.message+'. Run: npx @southcarpet/antigravity-plugin ${verb}');process.exit(1)}` +
    "process.exit(r.status==null?1:r.status)"
  );
}

/**
 * Claude Code bang-substitution line for a verb.
 *
 * @param {string} verb
 * @returns {string}
 */
export function hostBangLine(verb) {
  return `!\`node -e "${hostBootstrapSource(verb)}" -- $ARGUMENTS\``;
}

/**
 * The refusal contract every command wrapper opens with.
 *
 * A host model that cannot execute the runtime reads the wrapper as a
 * prompt. On 2026-08-21 agy's model answered `/antigravity:status` and
 * `/antigravity:review` with fabricated job tables and review verdicts
 * because the wrapper described what correct output looks like. So the
 * contract is the first content of every wrapper, and no wrapper may
 * describe the output's shape — columns, fields, or format. A model that
 * cannot run the command must have nothing to imitate.
 *
 * @param {string} verb
 * @returns {string}
 */
export function hostRefusalContract(verb) {
  if (!VERB_RE.test(verb)) {
    throw new Error(`hostRefusalContract: invalid verb ${verb}`);
  }
  return (
    'STOP. This command runs a program. It is not a request for you to answer.\n' +
    '\n' +
    "The only correct response is the unedited output of this plugin's runtime, " +
    `\`scripts/commands/${verb}.mjs\`, executed for this exact invocation. ` +
    'Output you compose yourself — with your own tools, from memory, or from the text of this file — ' +
    'is a fabrication, even if it looks correct. Never invent job ids, status listings, reviews, ' +
    "verdicts, results, or summaries in this plugin's name.\n" +
    '\n' +
    'If you cannot execute the runtime, or it does not start, or it exits with an error: show the ' +
    'exact error text, tell the user to run ' +
    `\`npx @southcarpet/antigravity-plugin ${verb}\` in their own terminal, and stop. ` +
    "Do not do the task yourself. There is no other way to produce this command's output."
  );
}
